# HPE PCAI platform integrations
ezua:
  domainName: "${DOMAIN_NAME}"
  virtualService:
    endpoint: "playground.${DOMAIN_NAME}"
  adminGroup: "admin"
  authorizationPolicy:
    namespace: "istio-system"
    matchLabels:
      hpe-ezua/type: vendor-service

podAnnotations:

# Default values for playground.
backend:
  replicaCount: 1
  image:
    repository: erdincka/playground-backend
    pullPolicy: Always
    tag: "0.1.18"
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 1
  image:
    repository: erdincka/playground-frontend
    pullPolicy: Always
    tag: "0.1.17"
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi

toolbox:
  image: "erdincka/playground-toolbox:0.1.6"

postgresql:
  enabled: true
  host: postgres
  port: 5432
  username: user
  # password: password # Deprecated, use auth.password
  database: playground
  auth:
    # If existingSecret is set, we use it. Otherwise we create one with this password.
    existingSecret: ""
    # The key in the secret that contains the password
    secretKey: "password"
    # The password to use if creating a new secret
    password: "password"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi