# HPE PCAI platform integrations
ezua:
  domainName: "${DOMAIN_NAME}"
  virtualService:
    endpoint: "playground.${DOMAIN_NAME}"
  adminGroup: "admin"
  authorizationPolicy:
    namespace: "istio-system"
    matchLabels:
      hpe-ezua/type: vendor-service

podAnnotations:

# Default values for playground.
backend:
  replicaCount: 1
  image:
    repository: erdincka/playground-backend
    pullPolicy: Always
    tag: "0.1.15"
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 1
  image:
    repository: erdincka/playground-frontend
    pullPolicy: Always
    tag: "0.1.12"
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi

toolbox:
  image: "erdincka/playground-toolbox:0.1.6"

postgresql:
  enabled: true
  host: postgres
  port: 5432
  username: user
  password: password
  database: playground
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
