apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playground-sandbox-viewer
rules:
  - apiGroups: ["kyverno.io"]
    resources: ["clusterpolicies", "policies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers", "issuers", "certificates"]
    verbs: ["get", "list", "watch"]