apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "playground.fullname" . }}-api-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "delete", "get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges", "pods", "services", "persistentvolumeclaims", "serviceaccounts", "secrets", "pods/exec", "pods/log"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "playground.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "playground.fullname" . }}-api-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "playground.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "playground.fullname" . }}-api-role
  apiGroup: rbac.authorization.k8s.io