apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-rbac-policy
spec:
  action: DENY
  selector:
    {{- with .Values.ezua.authorizationPolicy.matchLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  rules:
    - to:
        - operation:
            paths: ["/admin*"]
      when:
        - key: request.headers[x-auth-request-groups]
          notValues: ["*{{ .Values.ezua.adminGroup }}*"]