{{- if not .Values.postgresql.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playground.fullname" . }}-db-secret
  labels:
    {{- include "playground.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | default "password" | quote }}
{{- end -}}